#!/bin/sh
set -o errexit
echo -n 'version: '
read VERSION
echo -n 'min core version: '
read MINIMUM_CORE_VERSION
echo -n 'max core version: '
read COMPATIBLE_CORE_VERSION
cat >module.json <<EOF
{
   "name" : "lang-de",
   "title" : "German [Core]",
   "version" : "$VERSION",
   "minimumCoreVersion" : "$MINIMUM_CORE_VERSION",
   "compatibleCoreVersion" : "$COMPATIBLE_CORE_VERSION",
   "author" : "Hydroxi, lutece, henry4k",
   "description" : "German language support for Foundry VTT",
   "languages" : [
      {
         "lang" : "de",
         "name" : "German",
         "path" : "de.json"
      }
   ],
   "packs" : [],
   "scripts" : [],
   "styles" : [],
   "url" : "https://gitlab.com/henry4k/foundryvtt-lang-de",
   "manifest" : "https://gitlab.com/henry4k/foundryvtt-lang-de/-/raw/master/module.json",
   "download" : "https://gitlab.com/henry4k/foundryvtt-lang-de/-/jobs/artifacts/v$VERSION/download?job=build"
}
EOF
git add --all
git commit -m "Released version $VERSION"
git tag --force "v$VERSION"
git push --tags --force
